# Configuration for AutoChunkLoaderAdvance

chunkLoadRadius: 1 # How many chunks should be loaded around minecart/redstone signal (should be > 0)
maxLoadedChunks: 1000 # How many chunks can be force loaded
debugLog: false # Enable to find where is "lag machine"
unloadDelay: 30000 # Delay how long force loaded chunks should be loaded (in milliseconds)
unloadPeriod: 20 # How often to try unloading chunks (in ticks)
warningCooldown: 30000 # Limit reach repeat cooldown (in milliseconds)
backupPeriod: 120000 # Backup period (in milliseconds)
disableWarnings: false
disableRedstone: false
disableMinecarts: false
disableObservers: false
disableHoppers: false  # load's chunk when hoppers move items somewhere

# If filter mode set to `whitelist` plugin will be enabled for specified worlds
# If `blacklist` it will be disabled in specified worlds
worldFilterMode: "whitelist"
worlds:
  - "world"
  - "world_nether"
  - "world_the_end"